server:
  port: 4001
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "postgres"
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL